### ISSUE TITLE
Audio Extraction?

### ISSUE THREAD

**Issue by drewauff** [seanbreckenridge/mpvf#1]
Would be great if you could add a flag or the ability to extract/download audio/video to whatever bitrate/resolution we want?

**Comment by purarue** [comment]
Sure, that would require you have [youtube-dl](https://github.com/ytdl-org/youtube-dl) (see for instructions) installed as well, which you likely already do, if mpvf is working? Im not sure how mpv embeds/installs youtube-dl. Otherwise if you have python installed, you can likely just do `python3 -m pip install youtube-dl`, and you should be able to run `youtube-dl` then (assuming [the bin is on your path](https://unix.stackexchange.com/questions/612779/warning-not-on-path-when-i-tried-to-install-python-extensions-im-new-to-linu))

If you want to convert the result to mp3 from the m4a/opus file, also need to install [ffmpeg](https://ffmpeg.org/), but added a environment variable to enable this:

```
$ MPVF_DL=1 ./mpvf 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' --audio-format=mp3 --extract-audio
[mpvf] Downloading formats...
[mpvf] Format: 140
[mpvf] Running ytdl hook to stream with mpv...
[youtube] dQw4w9WgXcQ: Downloading webpage
[download] Destination: Rick Astley - Never Gonna Give You Up (Official Music Video).m4a
[download] 100% of 3.27MiB in 00:57
[ffmpeg] Correcting container in "Rick Astley - Never Gonna Give You Up (Official Music Video).m4a"
[ffmpeg] Destination: Rick Astley - Never Gonna Give You Up (Official Music Video).mp3
Deleting original file Rick Astley - Never Gonna Give You Up (Official Music Video).m4a (pass -k to keep)
```

(If you don't specify to `--extract-audio`, it'll just download the video as normal, assuming you pick a format which has it)

The additional flags in this case are [youtube-dl flags](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#readme), not mpv flags

**Comment by purarue** [comment]
Didnt want to add additional flags since woud get much more confusing/complicated with handling mpv vs youtube-dl flags, could put something in your shell profile like:

`alias mpvf-dl='MPVF_DL=1 mpvf'`

to make this nice to autocomplete

**Comment by drewauff** [comment]
I tried exactly what you said, even used the url from above, still only showing videos.

For the moment Im just trying to get it to display mp3's not so much the extraction.

I guess another option is to list all formats available? ie. videos, audio etc

**Comment by purarue** [comment]
If you want audio only, need to select a format that has that. Not  sure if theres something going on because of copyright on music, try with another URL:

```
$ youtube-dl -F 'https://youtu.be/SBeYzoQPbu8'
[youtube] SBeYzoQPbu8: Downloading webpage
[info] Available formats for SBeYzoQPbu8:
format code  extension  resolution note
249          webm       audio only tiny   53k , webm_dash container, opus @ 53k (48000Hz), 21.62KiB
250          webm       audio only tiny   72k , webm_dash container, opus @ 72k (48000Hz), 29.25KiB
140          m4a        audio only tiny   96k , m4a_dash container, mp4a.40.2@ 96k (44100Hz), 39.48KiB
251          webm       audio only tiny  104k , webm_dash container, opus @104k (48000Hz), 42.27KiB
160          mp4        144x144    144p   32k , mp4_dash container, avc1.4d400b@  32k, 30fps, video only, 12.21KiB
278          webm       144x144    144p   52k , webm_dash container, vp9@  52k, 30fps, video only, 19.96KiB
394          mp4        144x144    144p   54k , mp4_dash container, av01.0.00M.08@  54k, 30fps, video only, 20.72KiB
133          mp4        240x240    240p   55k , mp4_dash container, avc1.4d400d@  55k, 30fps, video only, 20.89KiB
395          mp4        240x240    240p   67k , mp4_dash container, av01.0.00M.08@  67k, 30fps, video only, 25.62KiB
242          webm       240x240    240p   87k , webm_dash container, vp9@  87k, 30fps, video only, 33.11KiB
396          mp4        360x360    360p  109k , mp4_dash container, av01.0.00M.08@ 109k, 30fps, video only, 41.50KiB
134          mp4        360x360    360p  132k , mp4_dash container, avc1.4d4015@ 132k, 30fps, video only, 50.03KiB
243          webm       360x360    360p  152k , webm_dash container, vp9@ 152k, 30fps, video only, 57.72KiB
18           mp4        360x360    360p  317k , avc1.42001E, 30fps, mp4a.40.2 (44100Hz), 129.44KiB (best)
```

Some of those should have 'audio only', e.g. 251

youtube doesnt have mp3's, it should download a m4a/opus if not given anything to convert it to, which is why I included the flags to do the conversion with ffmpeg

```
$ MPVF_DL=1 mpvf 'https://youtu.be/SBeYzoQPbu8' --audio-format=mp3 --extract-audio
[mpvf] Downloading formats...
[mpvf] Format: 251
[mpvf] Running ytdl hook to stream with mpv...
[youtube] SBeYzoQPbu8: Downloading webpage
[download] Destination: name a yellow fruit.webm
[download] 100% of 42.27KiB in 00:00
[ffmpeg] Destination: name a yellow fruit.mp3
Deleting original file name a yellow fruit.webm (pass -k to keep)
```

**Comment by drewauff** [comment]
[mpvf] Downloading formats...
[mpvf] Format: 140
[mpvf] Running ytdl hook to stream with mpv...
Error parsing option extract-audio (option not found)
Setting commandline option --extract-audio= failed.
Exiting... (Fatal error)

**Comment by purarue** [comment]
Try with 251 instead of 140 -- have had some forbidden issues on 140
Also what command are you running (you need to include the `MPVF_DL=1` if youre not)

**Comment by drewauff** [comment]
tried both.

cut & paste you command from above.

**Comment by purarue** [comment]
Oh -- I may have not made this clear enough, sorry

I [pushed a new commit](https://github.com/seanbreckenridge/mpvf/commit/6b3e204d6ea169045e7d5af0de5717e3d9578565) which adds this functionality, you have to reinstall the script

**Comment by drewauff** [comment]
Oh wow that was quick..

So, in terms of the new functionality. Do I use the same command?

**Comment by purarue** [comment]
Yeah, if the `MPVF_DL` variable is present, it uses `youtube-dl` to download, if it isn't, it uses `mpv` to stream it.

So you should be able to test it with: `MPVF_DL=1 mpvf 'https://youtu.be/SBeYzoQPbu8' --audio-format=mp3 --extract-audio`

**Comment by drewauff** [comment]
yup works perfectly!...

Had to install AtomicParsley, but it works.

btw, is it possible to list only audio?

**Comment by purarue** [comment]
Can always type 'audio only' into the fzf query, but I assume thats not what you mean

If you want a quick solution, copy the script and change the line here like:

```diff
diff --git a/mpvf b/mpvf
index b4dc097..89a2562 100755
--- a/mpvf
+++ b/mpvf
@@ -53,7 +53,7 @@ fi
 YOUTUBE_DL_FORMATS=$(echo "$YOUTUBE_DL_FORMATS_RAW" | grep -v "^\[") # remove progress info
 YOUTUBE_DL_FORMATS_TITLE=$(echo "$YOUTUBE_DL_FORMATS" | head -n 1)   # get format title
 
-YOUTUBE_DL_FORMATS_BODY=$(echo "$YOUTUBE_DL_FORMATS" | sed -e "1d")
+YOUTUBE_DL_FORMATS_BODY=$(echo "$YOUTUBE_DL_FORMATS" | sed -e "1d" | grep 'audio only')
 
 # prompt user to select format
 case "$PICKER" in
```

And rename that to  `mpvf-audio` or something

Could be something I add down the line, but providing additional flags in addition to mpv/youtube-dl stuff would likely involve rewriting this a bit

**Comment by drewauff** [comment]
Yup, gets the job done!

Thankyou..going to tinker with it a little to see if I can fix the label alignment.

**Comment by drewauff** [comment]
just a thought the "Format Code" is not really needed (for me)..so I tried to "awk" it out using `awk '{$1""; print $0}'` tried other things but no go.

After that all thats needed is to improve sorting ie. sort by extension then resolution/bitrate.

**Comment by purarue** [comment]
Feel free to open another issue if theres something else unrelated to this you think could improve this
